### PR TITLE
add signup for vendors

### PR DESCRIPTION
**Pull request by manzif**
### What does this PR do?
Signup for a new vendor

### Description of Task to be completed?
For all new vendor you can signup by providing firstname, lastname, email and password. If you already have an account it won't work.

• GET /api/vendors
• GET /api/members
• POST /api/vendors

### How should this be manually tested?
`npm start` to run the project and you will be able to signup

### CODE REVIEW

**Review by j4l13n — APPROVED** [review]

**Review by adafia — APPROVED** [review]

**Review by Emile-Nsengimana — CHANGES_REQUESTED** [review]
Why didn't you make validation a middle-ware?

**Review by Dom58 — COMMENTED** [review]
* Loop all validation errors 
* Use validation in routes
* Don't forget to leave an empty line to every file

**Review by adafia — COMMENTED** [review]
There are a few conflicting changes, please resolve them.

**Review by Dom58 — COMMENTED** [review]
Remove unwanted codes generated

**Review by Emile-Nsengimana — APPROVED** [review]

**Review by Dom58 — APPROVED** [review]

**Pull request merged**
