### PR TITLE
Ft signin

### PR DESCRIPTION
**Pull request by Emile-Nsengimana**
#### What does this PR do?
* allow a registered vendor to sign in
#### Description of Task to be completed?
* a register vendor should be able to sign in (with the correct email, password)
#### How should this be manually tested?
- First clone it to your machine:
```
https://github.com/j4l13n/vendorPro.git
```
- Open it using your favorite IDE
I recomend([vs code](https://code.visualstudio.com/download))

- Install all necessary node modules
```
npm install
```
- To start the app
```
npm start
```
- Use [postman](https://www.getpostman.com/downloads/) for testing the following endpoint
##### API ENDPOINTS
| API | Methods  | Description  |
| ------- | --- | --- |
| `/api/login` | POST | vendor signin |
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- N/A
#### Screenshots (if appropriate)
- N/A
#### Questions:

### CODE REVIEW

**Review by j4l13n — APPROVED** [review]

**Review by adafia — APPROVED** [review]

**Review by manzif — APPROVED** [review]

**Review by Dom58 — APPROVED** [review]

**Comment by kipropbrian** [comment]
The commit message did not follow our agreed on standards, please look into it

**Comment by kipropbrian** [comment]
Why do you have such lines? 
`// vendor signin tests -----------------------------------------------------`

**Comment by j4l13n** [comment]
We have already merged the PR. can we change that in our next PR?


> Why do you have such lines?
> `// vendor signin tests -----------------------------------------------------`

We have already merged the PR. Can we change that in our next PR?

**Comment by j4l13n** [comment]
> Why do you have such lines?
> `// vendor signin tests -----------------------------------------------------`

We have already merged the PR. Can we change that in our next PR?

**Pull request merged**
